# Generated by Django 6.0.4 on 2026-06-10 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('website', models.TextField()),
                ('About_us', models.TextField()),
                ('Email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('linkedIn', models.TextField()),
                ('position', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
