# Generated by Django 6.0.4 on 2026-06-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employerprofile',
            table='employer_profile',
        ),
    ]
