# Generated by Django 6.0.4 on 2026-06-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_alter_employerprofile_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='About_us',
            new_name='about_us',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='linkedIn',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='position',
            new_name='office_held',
        ),
        migrations.AlterModelTable(
            name='employerprofile',
            table=None,
        ),
    ]
