# Generated by Django 6.0.4 on 2026-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0004_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='Open', max_length=20),
        ),
    ]
